### ISSUE TITLE
Unable to compile with Rust nightly

### ISSUE THREAD

**Issue by alecho** [pleco-rs/Pleco#125]
System Version: macOS 10.14.6 (18G103)
Kernel Version: Darwin 18.7.0
rustc 1.41.0-nightly (25d8a9494 2019-11-29)
Git: master, 0.1.5, 0.1.6

```
error[E0635]: unknown feature `const_slice_len`
  --> pleco/src/lib.rs:77:42
   |
77 | #![cfg_attr(feature = "nightly", feature(const_slice_len))]
   |                                          ^^^^^^^^^^^^^^^
```

**Comment by MackEdweise** [comment]
Hey alecho, I have a branch on my fork which I have tweaked so that it is compiling on the nightly channel. 👍 
https://github.com/MackEdweise/Pleco/tree/compile-nightly

**Comment by abdulbadii** [comment]
me too on any, stable, beta, nightly

**Comment by SnowballSH** [comment]
Same on my windows 64-bit machine.

**Comment by chase-manning** [comment]
@alecho It looks like this project isn't maintained anymore, I've forked the repo and redeployed the crates, you can find them here:
- [Repo](https://github.com/chase-manning/tanton)
- [Tandon Crate (Pleco Crate)](https://crates.io/crates/tanton/)
- [Tandon Engine Crate (Pleco Engine Crate)](https://crates.io/crates/tanton_engine)

This issue should be fixed in this new version and releases.

**Comment by chase-manning** [comment]
@alecho @abdulbadii @SnowballSH This is fixed now 😄
