### ISSUE TITLE
Doesn't Compile due to const_fn feature having been removed

### ISSUE THREAD

**Issue by duganc** [pleco-rs/Pleco#137]
It looks like compilation (on Nightly, release) is failing due to:

```

error[E0557]: feature has been removed
  --> pleco_engine\src/lib.rs:24:12
   |
24 | #![feature(const_fn)]
   |            ^^^^^^^^ feature has been removed
   |
   = note: split into finer-grained feature gates

```

**Comment by jbgriesner** [comment]
PR done: https://github.com/sfleischman105/Pleco/pull/138

**Comment by chase-manning** [comment]
@duganc @jbgriesner  It looks like this project isn't maintained anymore, I've forked the repo and redeployed the crates, you can find them here:
- [Repo](https://github.com/chase-manning/tanton)
- [Tandon Crate (Pleco Crate)](https://crates.io/crates/tanton/)
- [Tandon Engine Crate (Pleco Engine Crate)](https://crates.io/crates/tanton_engine)

This issue should be fixed in this new version and releases.

**Comment by chase-manning** [comment]
@duganc @jbgriesner This has been fixed now 😄
